import express from 'express'

const app = express()
const port = 3000

app.use(express.static("public"))

// custom middleware
const randomName = (req, res, next) => {
  const randomAdjective = adjective[Math.floor(Math.random() * adjective.length)]
  const randomNoun = noun[Math.floor(Math.random() * noun.length)]
  req.bandName = `${randomAdjective} ${randomNoun}`
  next()
}
app.use(randomName)

app.get("/", (req, res) => {
  res.render("index.ejs")
})

app.post("/submit", (req, res) => {
  res.render("index.ejs", { bandName: req.bandName })
})

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`)
})

const adjective = [
"able", "absolute", "academic", "acceptable", "accurate", "aching", "acidic", "acrobatic", "active", "actual", 
"adept", "adorable", "adventurous", "affectionate", "ageless", "agile", "aggressive", "airy", "alert", "alive", 
"alluring", "aloof", "altruistic", "amazing", "ambitious", "amiable", "ample", "ancient", "angry", "animated", 
"annoying", "anxious", "apathetic", "appetizing", "apprehensive", "appropriate", "apt", "arctic", "ardent", "arrogant", 
"artistic", "ashamed", "astonishing", "astounding", "athletic", "atomic", "attentive", "audacious", "average", "avid", 
"awake", "aware", "awesome", "awful", "awkward", "baffled", "balanced", "balmy", "bare", "bashful", 
"basic", "beautiful", "belligerent", "beneficial", "benevolent", "big", "bitter", "bizarre", "black", "bland", 
"blank", "blatant", "blazing", "blessed", "blind", "blissful", "blond", "bloody", "blue", "blurry", 
"boastful", "bold", "bored", "boring", "bouncy", "boundless", "brainy", "brave", "brazen", "breezy", 
"brief", "bright", "brilliant", "brisk", "brittle", "broad", "broken", "bubbly", "bulky", "bumpy", 
"burly", "bustling", "busy", "candid", "caring", "casual", "caustic", "cautious", "celestial", "certain", 
"charming", "chatty", "cheap", "cheerful", "chemical", "chilly", "chubby", "chunky", "circular", "classic", 
"clean", "clear", "clever", "clinical", "close", "cloudy", "clumsy", "coarse", "coastal", "cold", 
"colorful", "colossal", "comforting", "common", "compassionate", "competent", "complex", "composed", "comprehensive", "conceited", 
"concerned", "concise", "confident", "confused", "conscientious", "conscious", "considerate", "consistent", "constant", "contemptuous", 
"content", "conventional", "cooperative", "coordinated", "correct", "courageous", "courteous", "crafty", "crazy", "creative", 
"credible", "creepy", "crisp", "critical", "crooked", "crucial", "crude", "cruel", "cuddly", "cultural", 
"cunning", "curious", "curly", "current", "cushy", "cute", "cylindrical", "daily", "dainty", "damaged", 
"damp", "dandy", "dangerous", "daring", "dark", "dashing", "daunting", "dazzling", "dead", "deadly", 
"deaf", "decent", "deceptive", "decisive", "deep", "defenseless", "defensive", "deliberate", "delicate", "delicious", 
"delightful", "demanding", "dense", "dependent", "depressed", "descriptive", "deserted", "detailed", "determined", "devilish", 
"dexterous", "diagonal", "different", "difficult", "diligent", "dim", "dimpled", "direct", "dirty", "disagreeable", 
"discreet", "dishonest", "disloyal", "dismal", "distant", "distinct", "distinguished", "distraught", "diverse", "divine", 
"dizzy", "dominant", "domestic", "dopey", "dormant", "double", "doubtful", "downright", "drab", "dramatic", 
"dreamy", "dreary", "driven", "drowsy", "dry", "dull", "durable", "dusty", "dutiful", "dynamic", 
"eager", "early", "earnest", "easy", "eccentric", "echoing", "economic", "ecstatic", "edgy", "educational", 
"eerie", "effective", "efficient", "elaborate", "elastic", "elderly", "electric", "elegant", "elementary", "elliptical", 
"eloquent", "elusive", "embarrassed", "eminent", "emotional", "empty", "enchanting", "encouraging", "energetic", "enormous", 
"enthusiastic", "entire", "envious", "equal", "equatorial", "erratic", "essential", "eternal", "ethereal", "ethical", 
"even", "everlasting", "everyday", "evil", "exacting", "excellent", "exceptional", "excessive", "excitable", "excited", 
"exciting", "exclusive", "exotic", "expensive", "experienced", "expert", "explicit", "exploratory", "explosive", "expressive", 
"exquisite", "extensive", "external", "extraordinary", "extravagant", "fabulous", "faint", "fair", "faithful", "false", 
"familiar", "famous", "fancy", "fantastic", "far", "fast", "fatal", "fatherly", "faulty", "fearful", 
"fearless", "feeble", "festive", "fickle", "fierce", "fiery", "final", "financial", "fine", "firm", 
"first", "fit", "fixed", "flaky", "flamboyant", "flashy", "flat", "flawless", "flexible", "flimsy", 
"flippant", "flowery", "fluffy", "fluid", "flustered", "focused", "foggy", "fond", "foolish", "forbidding", 
"forceful", "forgetful", "formal", "fortunate", "fragile", "fragrant", "frantic", "freaky", "free", "frequent", 
"fresh", "friendly", "frightened", "frightening", "frigid", "frivolous", "frosty", "frugal", "fruitful", "full", 
"funny", "futile", "fuzzy", "gargantuan", "gastronomic", "general", "generous", "gentle", "genuine", "geometric", 
"giddy", "gigantic", "gilded", "glacial", "glamorous", "glistening", "glorious", "glossy", "glowing", "good", 
"gorgeous", "graceful", "gracious", "grand", "grandiose", "grateful", "grave", "greasy", "great", "greedy", 
"green", "gregarious", "grim", "grimy", "grizzly", "gross", "grotesque", "grouchy", "growing", "grumpy", 
"guilty", "gullible", "gummy", "habitual", "hairy", "half", "halting", "handsome", "handy", "happy", 
"hard", "harmless", "harmonious", "harsh", "hasty", "healthy", "heartfelt", "heavenly", "heavy", "hefty", 
"helpful", "helpless", "hidden", "hideous", "high", "hilarious", "hissing", "historical", "hoarse", "hollow", 
"honest", "honorable", "hopeful", "horrible", "hospitable", "hot", "huge", "humble", "humorous", "hungry", 
"hurried", "hurtful", "hushed", "husky", "hyperactive", "hypnotic", "ideal", "identical", "idiotic", "ignorant", 
"ill", "illegal", "illogical", "imaginary", "immaculate", "immense", "imminent", "impartial", "imperfect", "impolite", 
"important", "impossible", "impressive", "impulsive", "inadequate", "inane", "inappropriate", "incandescent", "incisive", "inclusive", 
"incoherent", "incomplete", "inconclusive", "incredible", "independent", "indifferent", "ineffective", "inelegant", "inevitable", "infamous", 
"infantile", "inferior", "infinite", "informal", "innate", "innocent", "inquisitive", "insane", "insincere", "insipid", 
"instant", "instinctive", "insufficient", "intelligent", "intense", "intentional", "interested", "interesting", "internal", "intimate", 
"intrepid", "intricate", "invisible", "inviting", "irate", "ironic", "irrelevant", "irresponsible", "irritable", "itchy", 
"jaded", "jaunty", "jealous", "jittery", "jocular", "jovial", "joyful", "judicious", "juicy", "jumbo", 
"just", "juvenile", "keen", "kind", "kindhearted", "knowledgeable", "known", "labored", "lacy", "lame", 
"lanky", "large", "last", "late", "latter", "laudable", "lavish", "lazy", "lean", "legal", 
"legendary", "leisurely", "lengthy", "lenient", "level", "lewd", "light", "likeable", "limber", "limited", 
"linear", "liquid", "listless", "literate", "little", "lively", "loathsome", "lonely", "long", "loose", 
"loud", "lousy", "lovable", "lovely", "loving", "loyal", "lucky", "luminous", "lush", "luxurious", 
"lyrical", "macabre", "magnetic", "magnificent", "main", "majestic", "major", "male", "malicious", "mammoth", 
"maniacal", "manly", "many", "marble", "marvelous", "masculine", "massive", "materialistic", "mature", "meager", 
"meaningful", "mean", "mechanical", "meddling", "melancholy", "melodic", "memorable", "mental", "merciful", "merry", 
"messy", "metallic", "methodical", "meticulous", "mighty", "mild", "military", "mindful", "miniature", "minor", 
"miraculous", "mischievous", "misguided", "modern", "modest", "moist", "momentary", "monstrous", "monumental", "moody", 
"moral", "morbid", "moronic", "motionless", "motivational", "mountainous", "muddy", "mundane", "musical", "mushy", 
"mysterious", "mythical", "naive", "narrow", "nasty", "naughty", "nauseating", "nautical", "neat", "necessary", 
"negative", "neglected", "neighborly", "nervous", "neutral", "new", "next", "nice", "nifty", "nimble", 
"nocturnal", "noisy", "nonchalant", "normal", "nostalgic", "notable", "noteworthy", "novel", "noxious", "numb", 
"numerous", "nutritious", "obedient", "obese", "objective", "oblong", "obnoxious", "obscene", "obsequious", "observant", 
"obsolete", "obvious", "odd", "odorous", "offensive", "official", "oily", "old", "omniscient", "on-time", 
"open", "opulent", "orange", "ordinary", "organic", "original", "ornate", "ostentatious", "otherworldly", "outgoing", 
"outlandish", "outstanding", "oval", "overjoyed", "overwhelming", "painful", "pale", "panicked", "parallel", "paranoid", 
"passionate", "paternal", "patient", "patriotic", "peaceful", "peculiar", "pedantic", "pensive", "perceptive", "perfect", 
"periodical", "permanent", "perpetual", "personable", "persuasive", "petite", "petty", "physical", "picturesque", "piercing", 
"pink", "pious", "playful", "pleasant", "pleasing", "plump", "poetic", "pointless", "poised", "polite", 
"political", "poor", "popular", "portable", "positive", "possible", "powerful", "practical", "precious", "precise", 
"predictable", "preliminary", "premature", "premium", "prepared", "present", "prestigious", "pretty", "previous", "pricey", 
"prickly", "primary", "prime", "pristine", "private", "profound", "prominent", "promising", "proper", "proud", 
"provocative", "prudent", "psychic", "public", "puffy", "punctual", "pungent", "puny", "pure", "purple", 
"pushy", "puzzled", "puzzling", "quaint", "qualified", "quantifiable", "quick", "quiet", "quizzical", "radiant", 
"radical", "ragged", "rambunctious", "random", "rapid", "rare", "rash", "rational", "raw", "ready", 
"real", "realistic", "reasonable", "rebellious", "receptive", "reckless", "rectangular", "red", "reflective", "refreshing", 
"regal", "regular", "reliable", "relieved", "remarkable", "remote", "repulsive", "reputable", "resilient", "resourceful", 
"respectful", "responsible", "restless", "retired", "reclusive", "rich", "ridiculous", "rigid", "righteous", "ripe", 
"risky", "roaring", "robust", "romantic", "rosy", "rotund", "rough", "round", "rowdy", "royal", 
"rude", "rural", "rustic", "ruthless", "saccharine", "sad", "safe", "salty", "same", "sarcastic", 
"sassy", "satisfying", "savage", "scaly", "scared", "scary", "scattered", "scientific", "scrawny", "screaming", 
"scrupulous", "sculptural", "seamless", "seasoned", "secret", "secretive", "secure", "seductive", "sedentary", "selfish", 
"sensational", "sensible", "sensitive", "sensory", "sentimental", "separate", "serene", "serious", "salty", "shady", 
"shallow", "sharp", "shattered", "shiny", "shocking", "short", "showy", "shrewd", "shrill", "shy", 
"sick", "silent", "silky", "silly", "silver", "similar", "simple", "sincere", "sinful", "single", 
"singular", "sinister", "skeletal", "skillful", "skinny", "sleepy", "slender", "slight", "slimy", "sloppy", 
"slow", "small", "smart", "smelly", "smooth", "smug", "sneaky", "snobby", "soft", "solar", 
"solemn", "solid", "solitary", "somber", "sophisticated", "sore", "sorrowful", "soulful", "sour", "spacious", 
"sparkling", "special", "specific", "spectacular", "spicy", "spiritual", "spiteful", "splendid", "spotless", "spontaneous", 
"spooky", "sporty", "spotty", "square", "stable", "stale", "starry", "startling", "static", "statuesque", 
"steady", "steep", "sticky", "stiff", "stimulating", "stingy", "stormy", "straight", "strange", "strategic", 
"strong", "stubborn", "stunning", "stupendous", "stupid", "sturdy", "stylish", "subtle", "suburban", "successful", 
"sudden", "sultry", "sunny", "super", "superb", "superior", "supernatural", "supportive", "sure", "surprised", 
"surprising", "suspicious", "svelte", "swanky", "sweet", "swift", "symmetrical", "sympathetic", "systematic", "tall", 
"tangible", "tart", "tasteful", "tasty", "tawdry", "tearful", "teasing", "technical", "tedious", "teeny", 
"telling", "tenacious", "tender", "tense", "terrible", "terrific", "tertiary", "thankful", "therapeutic", "thick", 
"thin", "thorough", "thoughtful", "threadbare", "thrifty", "thrilling", "tidy", "tight", "timeless", "timid", 
"tiny", "tired", "tiresome", "top", "topical", "tough", "toxic", "traditional", "tranquil", "transparent", 
"tremendous", "tricky", "trim", "triangular", "troubled", "true", "trustworthy", "truthful", "tubular", "turbulent", 
"ugly", "ultimate", "unbiased", "unbelievable", "uncomfortable", "uncommon", "unconscious", "understated", "underrated", "uneven", 
"unexpected", "unfamiliar", "unfathomable", "unfit", "unfortunate", "unfriendly", "ungrateful", "unhealthy", "unimaginative", "unimportant", 
"uninterested", "unique", "united", "universal", "unkind", "unlawful", "unnecessary", "unpleasant", "unpredictable", "unreal", 
"unripe", "unruly", "unselfish", "unsightly", "unusual", "unwise", "upbeat", "upper", "upset", "urban", 
"urgent", "useful", "useless", "usual", "vacant", "vague", "vain", "valiant", "valid", "valuable", 
"variable", "various", "vast", "velvety", "vengeful", "verbal", "versatile", "vertical", "vibrant", "vicious", 
"victorious", "vigorous", "villainous", "violet", "violent", "viral", "virtual", "virtuous", "visible", "visionary", 
"vital", "vivid", "vocational", "voiceless", "voluminous", "voluntary", "vulnerable", "warm", "wary", "wasteful", 
"watery", "weak", "wealthy", "weary", "weird", "welcome", "well-known", "wet", "whimsical", "whirling", 
"whispering", "whole", "wicked", "wide", "widespread", "wild", "willing", "windy", "wise", "wistful", 
"witty", "wonderful", "wooden", "woozy", "wordy", "worldly", "worn", "worried", "worrying", "worthless", 
"worthy", "wretched", "wrinkled", "wrong", "xenophobic", "yearly", "yellow", "young", "youthful", "zany", 
"zealous", "zesty", "zigzag", "zonal"
]
const noun = [
"aardvark", "abacus", "abbey", "ability", "absence", "academy", "accord", "account", "ace", "acorn", 
"act", "action", "activity", "actor", "adage", "address", "adjective", "adult", "adventure", "advertisement", 
"advice", "aeroplane", "affair", "affliction", "afterlife", "age", "agency", "agenda", "agent", "agreement", 
"air", "airport", "aisle", "alarm", "album", "alley", "alliance", "alligator", "allowance", "alphabet", 
"ambulance", "amusement", "angel", "anger", "animal", "ankle", "answer", "ant", "apartment", "apology", 
"apparel", "apple", "application", "approach", "apron", "arch", "architect", "area", "argument", "arithmetic", 
"arm", "army", "aroma", "arrangement", "arrival", "arrow", "art", "article", "artist", "ash", 
"assembly", "assistant", "association", "assumption", "atmosphere", "attack", "attempt", "attention", "attitude", "audacity", 
"audience", "aunt", "authority", "avenue", "award", "baby", "back", "background", "backpack", "bacon", 
"badger", "bag", "baggage", "bait", "baker", "balance", "ball", "balloon", "banana", "band", 
"bank", "banner", "bar", "barber", "bark", "barn", "barrel", "barrier", "base", "basement", 
"basket", "basketball", "bat", "bath", "bathroom", "battle", "bay", "beach", "bead", "beam", 
"bean", "bear", "beard", "beast", "bed", "bedroom", "bee", "beef", "beer", "beetle", 
"beginner", "beginning", "behavior", "bell", "belt", "bench", "benefit", "berry", "bicycle", "bill", 
"bird", "birth", "birthday", "biscuit", "bit", "bite", "blade", "blanket", "bleach", "blessing", 
"blind", "blizzard", "block", "blood", "blossom", "blouse", "blow", "board", "boat", "body", 
"boil", "bomb", "bond", "bone", "book", "bookcase", "booklet", "boom", "boot", "border", 
"bottle", "boulder", "bottom", "bounty", "bow", "bowl", "box", "boy", "brain", "branch", 
"brand", "bravery", "bread", "break", "breakfast", "breath", "brick", "bridge", "brief", "brilliance", 
"broadcast", "brother", "brush", "bubble", "bucket", "budget", "buffer", "bug", "building", "bulb", 
"bull", "bullet", "bundle", "bureau", "bus", "bush", "business", "butter", "button", "buyer", 
"cabbage", "cabin", "cabinet", "cable", "cafe", "cage", "cake", "calculator", "calendar", "calf", 
"calm", "camera", "camp", "can", "canal", "candle", "candy", "cannon", "canvas", "cap", 
"capital", "capitol", "capsule", "car", "caravan", "card", "career", "care", "carpet", "carrot", 
"cart", "case", "cash", "castle", "cat", "catch", "caterpillar", "cathedral", "cause", "cave", 
"cedar", "ceiling", "cell", "cellar", "cement", "cemetery", "chain", "chair", "chalk", "challenge", 
"chamber", "champion", "chance", "change", "channel", "chaos", "chapter", "character", "charge", "charity", 
"chart", "chase", "chatter", "check", "cheek", "cheese", "chemical", "cherry", "chess", "chest", 
"chicken", "chief", "child", "chimney", "chin", "chocolate", "choice", "chord", "church", "circle", 
"circumstance", "city", "claim", "clash", "class", "classroom", "claw", "clay", "clerk", "cliff", 
"climate", "climb", "clock", "cloth", "clothes", "cloud", "clover", "club", "clue", "coal", 
"coast", "coat", "cobweb", "cockroach", "coffee", "coffin", "coil", "coin", "cold", "collar", 
"collection", "college", "colony", "color", "column", "comb", "combination", "comfort", "command", "comment", 
"committee", "communication", "community", "company", "comparison", "competition", "complaint", "complexity", "computer", "concept", 
"concern", "concert", "conclusion", "condition", "confusion", "connection", "conscience", "consent", "consequence", "container", 
"contempt", "contest", "context", "continent", "contract", "control", "conversation", "conviction", "cook", "cookie", 
"copper", "copy", "coral", "cord", "cork", "corn", "corner", "cost", "cottage", "cotton", 
"couch", "cough", "council", "counsel", "country", "courage", "course", "court", "cover", "cow", 
"crab", "crack", "cradle", "craft", "cram", "crane", "crate", "craving", "crawl", "cream", 
"creator", "creature", "creek", "crew", "crime", "criminal", "crisis", "criticism", "crocodile", "crop", 
"crow", "crowd", "crown", "crude", "crush", "cry", "crystal", "cube", "cuff", "cup", 
"cupboard", "curiosity", "curl", "currency", "curtain", "cushion", "custom", "customer", "cycle", "dad", 
"daffodil", "damage", "dance", "danger", "darkness", "data", "date", "daughter", "day", "dawn", 
"deal", "debt", "decade", "decay", "decision", "decrease", "deer", "defense", "degree", "delay", 
"delight", "delivery", "demand", "dentist", "department", "departure", "depression", "depth", "description", "desert", 
"design", "designer", "desire", "desk", "dessert", "destination", "detail", "determination", "development", "device", 
"devil", "diamond", "dictionary", "difference", "difficulty", "digestion", "dignity", "dinner", "dinosaur", "diploma", 
"direction", "director", "dirt", "disappointment", "disaster", "discipline", "discovery", "discussion", "disease", "disgrace", 
"dish", "disk", "display", "distance", "district", "diver", "division", "doctor", "document", "dog", 
"doll", "dollar", "dolphin", "donkey", "door", "doubt", "dough", "dove", "drama", "dream", 
"dress", "drink", "drive", "driver", "drop", "drum", "duck", "dust", "duty", "dwarf", 
"dynamite", "eagle", "ear", "earth", "earthquake", "ease", "east", "edge", "editor", "education", 
"effect", "effort", "egg", "eggplant", "elbow", "electricity", "element", "elephant", "elevator", "elf", 
"emotion", "emphasis", "employer", "employment", "end", "enemy", "energy", "engine", "engineer", "enigma", 
"enjoyment", "entrance", "entry", "environment", "episode", "era", "error", "escalator", "escape", "essay", 
"essence", "establishment", "estate", "ether", "event", "evidence", "evil", "evolution", "example", "excellence", 
"exchange", "excitement", "excuse", "exercise", "existence", "exit", "experience", "experiment", "expert", "explanation", 
"expression", "extension", "extent", "eye", "fabric", "face", "facility", "fact", "factor", "factory", 
"failure", "fairness", "faith", "fall", "fame", "family", "fan", "fantasy", "farm", "farmer", 
"fashion", "fate", "father", "fault", "favor", "fear", "feather", "feature", "fee", "feeling", 
"fence", "ferry", "festival", "fever", "fiction", "field", "fight", "figure", "file", "film", 
"finger", "fire", "fireplace", "firm", "fish", "fisher", "fist", "fit", "fitness", "flag", 
"flame", "flash", "flat", "flavor", "flesh", "flight", "flood", "floor", "flour", "flower", 
"fluid", "fly", "fog", "fold", "food", "foot", "football", "force", "forest", "fork", 
"form", "fortune", "foundation", "fountain", "fox", "fragrance", "frame", "freedom", "friend", "friendship", 
"frill", "fringe", "frog", "front", "fruit", "fuel", "fun", "function", "fund", "funeral", 
"fur", "furnace", "furniture", "gain", "galaxy", "game", "garage", "garden", "gas", "gate", 
"gem", "gender", "generation", "generosity", "genius", "gentleman", "geography", "ghost", "giant", "gift", 
"giraffe", "girl", "glance", "glass", "glove", "glow", "goal", "goat", "god", "gold", 
"good", "goose", "gossip", "government", "governor", "grace", "grade", "grain", "granddaughter", "grandfather", 
"grandmother", "grass", "gratitude", "grave", "gravel", "gravity", "grease", "greatness", "green", "grief", 
"grocery", "ground", "group", "growth", "guard", "guest", "guidance", "guide", "guilt", "guitar", 
"gum", "gun", "gym", "habit", "hair", "hall", "hammer", "hand", "handbag", "handle", 
"happiness", "harbor", "harm", "harmony", "hat", "haze", "head", "health", "heart", "heat", 
"heaven", "height", "helicopter", "hell", "helmet", "help", "hen", "hero", "hide", "highway", 
"hill", "history", "hit", "hobby", "hold", "hole", "holiday", "home", "homeland", "honor", 
"hook", "hope", "horizon", "horn", "horror", "horse", "hospital", "host", "hotel", "hour", 
"house", "household", "humor", "hunger", "hunt", "hurricane", "hurry", "husband", "ice", "idea", 
"identity", "idiom", "illness", "imagination", "impact", "importance", "impression", "improvement", "incident", "income", 
"increase", "independence", "index", "industry", "influence", "information", "injury", "ink", "inquiry", "insect", 
"inside", "inspiration", "instance", "instrument", "insurance", "interest", "interface", "internet", "introduction", "invasion", 
"invention", "investment", "iron", "island", "issue", "jacket", "jaguar", "jail", "jam", "jar", 
"jaw", "jeans", "jet", "jewel", "job", "join", "joke", "journal", "journey", "joy", 
"judge", "judgment", "juice", "jungle", "junk", "justice", "kangaroo", "kettle", "key", "keyboard", 
"kid", "kidney", "kind", "king", "kingdom", "kiss", "kitchen", "kite", "kitten", "knee", 
"knife", "knight", "knot", "knowledge", "lab", "labor", "ladder", "lady", "lake", "lamp", 
"land", "landlord", "language", "lark", "last", "latch", "laugh", "laughter", "law", "lawyer", 
"layer", "lead", "leadership", "leaf", "league", "leather", "lecture", "leg", "legend", "lemon", 
"length", "leopard", "lesson", "letter", "level", "library", "lie", "life", "lift", "light", 
"lightning", "limit", "line", "lion", "lip", "liquid", "list", "literacy", "literature", "loaf", 
"location", "lock", "log", "loneliness", "look", "loop", "lord", "loss", "lot", "love", 
"luck", "luggage", "lunch", "machine", "madness", "magazine", "magic", "magnet", "magnitude", "mail", 
"maintenance", "major", "mall", "man", "management", "manager", "mane", "manner", "manor", "manufacturer", 
"map", "march", "margin", "mark", "market", "mask", "mass", "master", "match", "mate", 
"material", "matter", "meal", "meaning", "measure", "meat", "mechanic", "media", "medicine", "melody", 
"member", "memory", "menu", "mercy", "mess", "message", "metal", "meteor", "method", "microscope", 
"midnight", "mind", "mine", "mineral", "minister", "minority", "minute", "miracle", "mirror", "misery", 
"mission", "mist", "mistake", "mix", "moat", "model", "mole", "moment", "money", "monster", 
"month", "monument", "moon", "morning", "mosquito", "mother", "motion", "motorcycle", "mountain", "mouse", 
"mouth", "move", "movie", "muffin", "mug", "muscle", "music", "mystery", "nail", "name", 
"nap", "nation", "nature", "necessity", "neck", "need", "needle", "negotiation", "nerve", "nest", 
"net", "network", "news", "newspaper", "night", "nightmare", "noise", "nonchalance", "note", "notebook", 
"nothing", "notice", "novel", "number", "nurse", "nut", "oar", "oath", "object", "objection", 
"observation", "ocean", "offer", "office", "officer", "oil", "opinion", "opportunity", "opposite", "option", 
"orange", "orchard", "orchestra", "order", "organization", "origin", "ornament", "ounce", "outcome", "outfit", 
"outlet", "outline", "outrage", "outside", "oven", "owl", "owner", "ownership", "oxygen", "pace", 
"package", "page", "pain", "paint", "pair", "palace", "pan", "paper", "paradise", "paragraph", 
"park", "part", "partner", "partnership", "pass", "passage", "passion", "passport", "past", "path", 
"patience", "patient", "pattern", "pavement", "payment", "peace", "peach", "peak", "pencil", "penguin", 
"penny", "people", "pepper", "perfection", "performance", "period", "permission", "person", "perspective", "pet", 
"phone", "photo", "photograph", "piano", "pick", "picnic", "picture", "pie", "pig", "pile", 
"pill", "pillow", "pilot", "pin", "pinch", "pine", "pipe", "pirate", "pistol", "pizza", 
"place", "plan", "planet", "plant", "plaster", "plastic", "plate", "platform", "play", "player", 
"pleasure", "plight", "plough", "pocket", "poem", "poet", "point", "poison", "police", "policy", 
"politics", "poll", "pond", "pool", "population", "portion", "portrait", "position", "possession", "post", 
"pot", "potato", "power", "practice", "praise", "prayer", "precision", "prejudice", "preparation", "presence", 
"present", "president", "pressure", "price", "pride", "priest", "primary", "prince", "princess", "principle", 
"print", "prison", "privilege", "prize", "problem", "process", "product", "production", "profession", "professor", 
"profit", "program", "progress", "project", "promise", "promotion", "proof", "property", "prose", "protest", 
"protection", "psychology", "public", "publication", "pull", "pulpit", "pulse", "pumpkin", "punch", "punishment", 
"pupil", "purchase", "purpose", "pursuit", "puzzle", "quality", "quantity", "quarter", "queen", "question", 
"quiet", "quill", "quilt", "rabbit", "race", "radio", "rage", "rain", "rainbow", "railway", 
"raincoat", "raise", "range", "rank", "rate", "ray", "razor", "reaction", "reader", "reading", 
"reality", "reason", "receipt", "receiver", "recipe", "recognition", "record", "recovery", "rectangle", "red", 
"reference", "reflection", "refrigerator", "regret", "regulation", "reindeer", "relation", "relationship", "relief", "religion", 
"remark", "remedy", "rent", "repair", "report", "reporter", "representative", "republic", "reputation", "request", 
"research", "reserve", "residence", "resolution", "resort", "resource", "respect", "response", "responsibility", "rest", 
"restaurant", "result", "retreat", "reunion", "revenge", "revenue", "reward", "rhythm", "ribbon", "rice", 
"rich", "ride", "ridge", "ring", "rise", "risk", "river", "road", "roast", "robber", 
"rock", "rocket", "rod", "roll", "roof", "room", "root", "rope", "rose", "rot", 
"round", "route", "routine", "row", "rule", "ruler", "rumor", "run", "rust", "sack", 
"sadness", "safety", "sail", "salad", "salary", "sale", "salt", "sample", "sand", "sandwich", 
"satisfaction", "sauce", "sausage", "saving", "scale", "scar", "scarecrow", "scene", "schedule", "school", 
"science", "scissors", "score", "scout", "scraps", "scratch", "scream", "screen", "screw", "script", 
"sea", "seafood", "seal", "season", "seat", "secret", "secretary", "section", "seed", "selection", 
"self", "sense", "sentence", "sentiment", "separation", "series", "service", "session", "set", "settlement", 
"shadow", "shake", "shame", "shape", "share", "shelf", "shell", "shelter", "shield", "ship", 
"shock", "shoe", "shop", "shopping", "shore", "short", "shot", "shoulder", "show", "shower", 
"shrimp", "sight", "sign", "signal", "signature", "silence", "silk", "silver", "simplicity", "singing", 
"sister", "situation", "size", "skill", "skin", "skirt", "sky", "slave", "sleep", "sleeve", 
"slide", "slip", "smell", "smile", "smoke", "snail", "snake", "snow", "snowball", "sock", 
"society", "soil", "soldier", "solution", "son", "song", "sort", "soul", "sound", "soup", 
"space", "spade", "spark", "speaker", "spear", "specialist", "speed", "spell", "spending", "spider", 
"spirit", "spite", "splinter", "spoke", "sport", "spot", "spring", "square", "stadium", "staff", 
"stage", "stair", "stamp", "stand", "star", "start", "state", "statement", "station", "status", 
"stay", "steam", "steel", "stem", "step", "stick", "stimulus", "stock", "stomach", "stone", 
"stop", "storage", "store", "storm", "story", "stove", "stranger", "strategy", "stream", "street", 
"strength", "stress", "stretch", "strike", "string", "structure", "struggle", "student", "studio", "study", 
"stuff", "style", "subject", "substance", "success", "sugar", "suggestion", "suit", "sun", "sunshine", 
"supermarket", "support", "surface", "surprise", "survival", "swan", "sweater", "sweatshirt", "sweet", "swim", 
"swing", "system", "table", "tail", "talent", "talk", "tank", "tap", "tape", "task", 
"taste", "tax", "taxi", "teacher", "team", "tear", "technology", "teenager", "telephone", "telescope", 
"television", "temperature", "temple", "tendency", "tennis", "tension", "tent", "term", "test", "text", 
"thanks", "theme", "theory", "thing", "thought", "thread", "threat", "throat", "throne", "throw", 
"thunder", "ticket", "tide", "tie", "tiger", "time", "tin", "tip", "tire", "title", 
"toe", "tomato", "tongue", "tooth", "top", "topic", "touch", "tour", "town", "toy", 
"track", "trade", "traffic", "train", "transaction", "transition", "transport", "trap", "travel", "tree", 
"trial", "tribe", "trick", "trip", "trouble", "truck", "trust", "truth", "tube", "tuna", 
"tunnel", "turn", "turtle", "tutor", "twin", "twist", "type", "umbrella", "uncle", "underground", 
"unit", "universe", "university", "upgrade", "urgency", "use", "utility", "vacation", "valley", "value", 
"van", "variety", "vegetable", "vehicle", "vein", "venue", "verse", "version", "vessel", "vest", 
"veteran", "veto", "vice", "victim", "victory", "video", "view", "village", "vine", "violet", 
"violin", "virus", "visa", "vision", "visit", "visitor", "voice", "vote", "vow", "walk", 
"wall", "wallet", "wand", "war", "wardrobe", "warmth", "warning", "wash", "waste", "watch", 
"water", "wave", "way", "weakness", "wealth", "weapon", "weather", "web", "week", "weight", 
"weird", "west", "whale", "wheat", "wheel", "whisper", "whistle", "white", "whole", "wife", 
"will", "wind", "window", "wine", "wing", "winner", "winter", "wire", "wisdom", "wish", 
"witness", "woman", "wood", "wool", "word", "work", "worker", "world", "worry", "worth", 
"wrap", "wreck", "wrist", "writer", "writing", "yard", "yawn", "year", "yellow", "youth", 
"zone", "zoo"
]
